fix ghosting and stuck screens in macOS
SnosMe/awakened-poe-trade pull request #1418
Opened 2024-08-02 20:22 UTC by vitor-jotave

enabling hardware acceleration fixed ghosting graphics and stuck screens in macOS for me, may help other mac players. 

(MacBook Pro, Sonoma, M2 Pro)

before enabling: https://drive.google.com/file/d/1PEqsYOH-KF3XNVdCYwIG9AoM1mu5gszL/view?usp=sharing

after enabling: https://drive.google.com/file/d/1AT8YLfjifYwG1i2UPa5WVVD_TwpJ7INo/view?usp=sharing

2024-08-02 20:40 UTC, SnosMe commented
That's... interesting.

2024-08-02 20:42 UTC, SnosMe requested changes

2024-08-02 20:42 UTC, SnosMe commented on main/src/main.ts
> -app.disableHardwareAcceleration()
if (platform != macOS) {} please

2024-08-02 21:05 UTC, vitor-jotave commented
there it is :)

2024-08-02 21:33 UTC, vitor-jotave commented on main/src/main.ts
> -app.disableHardwareAcceleration()
done

2024-08-06 16:29 UTC, davidtubehd commented
how do u enable hardware acceleration?

2024-08-07 16:45 UTC, marconett commented
can confirm that this patch fixes the issue.

2024-08-07 17:15 UTC, marconett commented
or rather: removing`app.disableHardwareAcceleration()` fixes the issue. the patch itself has syntax errors ..

2024-08-09 21:59 UTC, anstaendig commented
Any chance this will PR will get merged? :)

2024-08-10 05:23 UTC, SnosMe commented
Yes, it will ve

2024-08-10 23:55 UTC, flieee commented
[machwaccel.patch](https://github.com/user-attachments/files/16571158/machwaccel.patch)

Hi @SnosMe, @vitor-jotave, would this patch work?

2024-08-12 16:21 UTC, vitor-jotave commented
> [machwaccel.patch](https://github.com/user-attachments/files/16571158/machwaccel.patch)
> 
> Hi @SnosMe, @vitor-jotave, would this patch work?

seems like it should, up to @SnosMe though.

2024-09-08 09:17 UTC, closed without merging